version: "3.7"

services:
  db:
    image: mysql:5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql
      - ./db-init-scripts:/docker-entrypoint-initdb.d
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - '8181:80'
    environment:
      - PMA_ARBITRARY=1
  email:
    image: marcopas/docker-mailslurper
    ports:
      - '2500:2500'
      - '9090:8080'
      - '8085:8085'
volumes:
  my-db:
    name: mysql57